import {
    MatSelectModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatBadgeModule,
    MatCardModule,
    MatDialogModule,
    MatNativeDateModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatSlideToggleModule,
    MatListModule,
    MatMenuModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatToolbarModule,
    MatSidenavModule,
    MatExpansionModule,
    MatRippleModule,
    MatStepperModule,
    MatButtonToggleModule,
    MatRadioModule,
    MatTabsModule,
    MatTableModule,
    MatDatepickerModule
  } from '@angular/material';

import {MatChipsModule} from '@angular/material/chips';
import {MatTreeModule} from '@angular/material/tree';
import {NgModule} from '@angular/core';
import { SidebarComponent } from 'src/app/components/sidebar/sidebar.component';


@NgModule({
    imports: [
      MatSelectModule,
      MatCheckboxModule,
      MatRippleModule,
      MatBadgeModule,
      MatDialogModule,
      MatSlideToggleModule,
      MatChipsModule,
      MatTreeModule,
      MatButtonModule,
      MatMenuModule,
      MatIconModule,
      MatCardModule,
      MatSliderModule,
      MatProgressBarModule,
      MatAutocompleteModule,
      MatInputModule,
      MatGridListModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatTooltipModule,
      MatListModule,
      MatToolbarModule,
      MatSidenavModule,
      MatExpansionModule,
      MatStepperModule,
      MatButtonToggleModule,
      MatRadioModule,
      MatTabsModule,
      MatTableModule,
      MatNativeDateModule,
      MatDatepickerModule
    ],
    exports: [
      MatSelectModule,
      MatCheckboxModule,
      MatBadgeModule,
      MatSlideToggleModule,
      MatChipsModule,
      MatTreeModule,
      MatButtonModule,
      MatMenuModule,
      MatRippleModule,
      MatIconModule,
      MatCardModule,
      MatSliderModule,
      MatProgressBarModule,
      MatAutocompleteModule,
      MatInputModule,
      MatGridListModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatTooltipModule,
      MatListModule,
      MatDialogModule,
      MatToolbarModule,
      MatSidenavModule,
      MatExpansionModule,
      MatStepperModule,
      MatButtonToggleModule,
      MatRadioModule,
      MatTabsModule,
      MatTableModule,
      MatDatepickerModule
    ],
  })

  export class MaterialModule {
  }

